object_global_localizator:
#  cameraXCenter: 640.0
#  cameraYCenter: 360.0
#  cameraXMax: 1280.0
#  cameraYMax: 720.0
#  cameraXAngle: 0.873254
#  cameraYAngle: 0.463729

  cameraXCenter: 960.0
  cameraYCenter: 540.0
  cameraXMax: 1920.0
  cameraYMax: 1080.0
  cameraXAngle: 0.685696
  cameraYAngle: 0.4