3color:
  #   points
  pointALo: 149.164900
  pointALa: -35.3631731
  pointBLo: 149.164900
  pointBLa: -35.3624567
  pointCLo: 149.164400
  pointCLa: -35.3624567
  pointDLo: 149.164400
  pointDLa: -35.3631731

  numberOfPaths: 6

  #   altitudes
  lowFlyAlt: 10.0     # [m]
  flyAlt: 30.0        # [m]
  closeLookAlt: 5.0   # [m]
  #  conversions
  #  aslToWGS83: -33.5  # Łódź
  #  aslToWGS83: -37.0  # Kąkolewo
  aslToWGS83: -19.6   # Simulation Gazebo

  #   Accuracy
  waypointPositionAccuracy: 1.0   # [m]